# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# All the environment variables used in this file should be defined in
# the .env file so Dotenv can fetch them when the application starts.
# At least for development and test.

development:
  secret_key_base: 532715b299b7669ccac8cc01d694f0423822315c34d27e73becd0740654c129038812fee8ad8d5cfeadf8211bf0e38ee7a556206cd2cd4cce30fc4da9e81e37f
  smpt_sender: <%= ENV["SMTP_SENDER"] %>
  smtp_user_name: <%= ENV["SMTP_USER_NAME"] %>
  smtp_password: <%= ENV["SMTP_PASSWORD"] %>  
  facebook_app_id: <%= ENV["FACEBOOK_APP_ID"] %>
  facebook_app_secret: <%= ENV["FACEBOOK_APP_SECRET"] %>  
  twitter_app_id: <%= ENV["TWITTER_APP_ID"] %>
  twitter_app_secret: <%= ENV["TWITTER_APP_SECRET"] %>
  google_app_id: <%= ENV["GOOGLE_APP_ID"] %>
  google_app_secret: <%= ENV["GOOGLE_APP_SECRET"] %>
  
test:
  secret_key_base: 9b85b9739593d02ccc775dcfec9b4fe8c269e5d2e2d26aea92b156c140de12aa6d9a139a47b6f48594e73bc9cff85d57f3823806f52c16367e746f426e66635c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
