new_players = [
=begin  
  [ "Sead", "Kolasinac", nil, 110260, "1993-06-20", 183, 85, "Bosnia and Herzegovina"],
  [ "Alexandre", "Lacazette", nil, 73078, "1991-05-28", 175, 73, "France"],
  [ "Charlie", "Taylor", nil, 107462, "1993-09-18", 176, 79, "England"],
  [ "Antonio", "Rüdiger", nil, 104010, "1993-03-03", 190, 85, "Germany"],
  [ "Tiemoué", "Bakayoko", nil, 135211, "1994-08-17", 185, 77, "France"],
  [ "Charly", "Musonda", nil, 303172, "1996-10-15", 173, 66, "Belgium"],
  [ "Álvaro", "Morata", nil, 91213, "1992-10-23", 189, 85, "Spain"],
  [ "Jairo", "Riedewald", nil, 141246, "1996-09-09", 182, 79, "Netherlands"],
  [ "Davy", "Klaassen", nil, 108860, "1993-02-21", 179, 70, "Netherlands"],
  [ "Molla", "Wagué", nil, 105339, "1991-02-21", 191, 87, "Mali"],
  [ "Vicente", "Iborra", nil, 34052, "1988-01-16", 195, 88, "Spain"],
  [ "", "Ederson", "Ederson Santana de Moraes", 121774, "1993-08-17", 188, 86, "Brazil"],
  [ "", "Danilo", "Danilo Luiz da Silva", 88300, "1991-07-15", 184, 78, "Brazil"],
  [ "Benjamin", "Mendy", nil, 105962, "1994-07-17", 185, 85, "France"],
  [ "Bernardo", "Silva", "Bernardo Mota Veiga de Carvalho e Silva", 136741, "1994-08-10", 173, 64, "Portugal"],
  [ "Victor", "Lindelöf", nil, 100008, "1994-07-17", 187, 80, "Sweden"],
  [ "Jan", "Bednarek", nil, 136742, "1996-04-12", 189, 77, "Poland"],
  [ "Roque", "Mesa", nil, 108176, "1989-06-07", 171, 68, "Spain"],
  [ "Kiko", "Femenía", "Francisco Femenía Far", 75919, "1991-02-02", 176, 61, "Spain"],
  [ "Will", "Hughes", nil, 108638, "1995-04-17", 185, 74, "England"],
  [ "Ahmed", "Hegazi", "Ahmed El-Sayed Hegazi", 108724, "1991-01-25", 193, 83, "Egypt"],
  [ "Jesús", "Gámez", "Jesús Gámez Duarte", 18538, "1985-04-10", 182, 77, "Spain"],
  [ "Florian", "Lejeune", nil, 80758, "1991-05-20", 190, 81, "France"],
  [ "Niki", "Mäenpää", nil, 35565, "1985-01-23", 190, 86, "Finland"],
  [ "Mathew", "Ryan", nil, 81523, "1992-04-08", 184, 82, "Australia"],
  [ "Lewis", "Dunk", nil, 86441, "1991-11-21", 192, 88, "England"],
  [ "Uwe", "Hünemeier", nil, 14179, "1986-01-09", 189, 85, "Germany"],
  [ "", "Bruno", "Bruno Saltor Grau", 96471, "1980-01-10", 181, 76, "Spain"],
  [ "Gaëtan", "Bong", nil, 32720, "1988-04-25", 187, 74, "Cameroon"],
  [ "Connor", "Goldson", nil, 134258, "1992-12-18", 191, 85, "England"],
  [ "Markus", "Suttner", nil, 33477, "1987-04-16", 179, 73, "Austria"],
  [ "Dale", "Stephens", nil, 24238, "1989-06-12", 169, 71, "England"],
  [ "Beram", "Kayal", nil, 33318, "1988-05-02", 178, 74, "Israel"],
  [ "Solomon", "March", nil, 122926, "1994-07-20", 180, 88, "England"],
  [ "Jiri", "Skalak", nil, 90549, "1992-03-12", 177, 76, "Czech Republic"],
  [ "Jamie", "Murphy", nil, 25829, "1989-08-28", 178, 72, "Scotland"],
  [ "Pascal", "Groß", nil, 71824, "1991-06-15", 181, 78, "Germany"],
  [ "Tomer", "Hemed", nil, 28981, "1987-05-02", 186, 80, "Israel"],
  [ "Joel", "Coleman", nil, 135179, "1995-09-26", 198, 82, "England"],
  [ "Jonas", "Lössl", nil, 131171, "1989-02-01", 195, 89, "Denmark"],
  [ "Christopher", "Schindler", nil, 132360, "1990-04-29", 189, 82, "Germany"],
  [ "Chris", "Löwe", nil, 101664, "1989-04-16", 175, 68, "Germany"],
  [ "Michael", "Hefele", nil, 104035, "1990-09-01", 192, 89, "Germany"],
  [ "Jon Gorenc", "Stankovic", nil, 254128, "1996-01-14", 190, 78, "Slovenia"],
  [ "", "Zanka", "Mathias Jorgensen", 29026, "1990-04-23", 191, 79, "Denmark"],
  [ "Scott", "Malone", nil, 74077, "1991-03-25", 189, 75, "England"],
  [ "Aaron", "Mooy", nil, 318153, "1990-09-15", 174, 68, "Australia"],
  [ "Rajiv", "Van La Parra", nil, 42947, "1991-06-04", 181, 72, "Netherlands"],
  [ "Philip", "Billing", nil, 145277, "1996-06-11", 193, 83, "Denmark"],
  [ "Joe", "Lolley", nil, 138785, "1992-08-25", 178, 72, "England"],
  [ "Harry", "Bunn", nil, 140859, "1992-11-21", 175, 74, "England"],
  [ "Sean", "Scannell", nil, 33366, "1990-09-17", 175, 73, "Ireland"],
  [ "Elias", "Kachunga", nil, 92804, "1992-04-22", 178, 74, "Congo, Democratic Republic of the"],
  [ "Danny", "Williams", nil, 83335, "1989-03-08", 182, 79, "USA"],
  [ "Nahki", "Wells", nil, 122554, "1990-06-01", 170, 69, "Bermuda"],
  [ "Collin", "Quaner", nil, 90996, "1991-06-18", 191, 81, "Germany"],
  [ "Laurent", "Depoitre", nil, 106880, "1988-12-07", 191, 91, "Belgium"],
  [ "Steve", "Mounie", nil, 135259, "1994-09-29", 190, 83, "Benin"],
=end
]

puts("Seeding new players...")

new_players.each do |first_name, last_name, full_name, whoscored_id, date_of_birth, height, weight, country_name|
  country = Country.where(name: country_name).first
  if country.nil? then
    puts "Could not find country #{country_name}"
    country = Country.find(1)
  end
  Player.create(first_name: first_name, last_name: last_name, country: country, date_of_birth: date_of_birth, height: height, weight: weight, full_name: full_name, whoscored_id: whoscored_id)
end

players = [
  [ "Alexis Sánchez", "ARS", "MID" ],
  [ "Özil", "ARS", "MID" ],
  [ "Petr Cech", "ARS", "GKP" ],
  [ "Walcott", "ARS", "MID" ],
  [ "Koscielny", "ARS", "DEF" ],
  [ "Bellerín", "ARS", "DEF" ],
  [ "Giroud", "ARS", "FWD" ],
  [ "Monreal", "ARS", "DEF" ],
  [ "Mustafi", "ARS", "DEF" ],
  [ "Iwobi", "ARS", "MID" ],
  [ "Xhaka", "ARS", "MID" ],
  [ "Calum Chambers", "ARS", "DEF" ],
  [ "Oxlade-Chamberlain", "ARS", "MID" ],
  [ "Wilshere", "ARS", "MID" ],
  [ "Ramsey", "ARS", "MID" ],
  [ "Coquelin", "ARS", "MID" ],
  [ "Gabriel Paulista", "ARS", "DEF" ],
  [ "Kieran Gibbs", "ARS", "DEF" ],
  [ "Cazorla", "ARS", "MID" ],
  [ "Welbeck", "ARS", "FWD" ],
  [ "Holding", "ARS", "DEF" ],
  [ "Elneny", "ARS", "MID" ],
  [ "Lucas Pérez", "ARS", "FWD" ],
  [ "Ospina", "ARS", "GKP" ],
  [ "Jenkinson", "ARS", "DEF" ],
  [ "Mertesacker", "ARS", "DEF" ],
  [ "Kolasinac", "ARS", "DEF" ],
  [ "Lacazette", "ARS", "FWD" ],
    
  [ "Joshua King", "BOR", "FWD" ],
  [ "Defoe", "BOR", "FWD" ],
  [ "Charlie Daniels", "BOR", "DEF" ],
  [ "Boruc", "BOR", "GKP" ],
  [ "Steve Cook", "BOR", "DEF" ],
  [ "Stanislas", "BOR", "MID" ],
  [ "Adam Smith", "BOR", "DEF" ],
  [ "Ryan Fraser", "BOR", "MID" ],
  [ "Simon Francis", "BOR", "DEF" ],
  [ "Afobe", "BOR", "FWD" ],
  [ "Harry Arter", "BOR", "MID" ],
  [ "Marc Pugh", "BOR", "MID" ],
  [ "Callum Wilson", "BOR", "FWD" ],
  [ "Nathan Aké", "BOR", "DEF" ],
  [ "Gosling", "BOR", "MID" ],
  [ "Surman", "BOR", "MID" ],
  [ "Jordon Ibe", "BOR", "MID" ],
  [ "Lewis Cook", "BOR", "MID" ],
  [ "Mousset", "BOR", "FWD" ],
  [ "Federici", "BOR", "GKP" ],
  [ "Gradel", "BOR", "MID" ],
  [ "Tyrone Mings", "BOR", "DEF" ],
  [ "Brad Smith", "BOR", "DEF" ],
  [ "Begovic", "BOR", "GKP" ],
  
  [ "Heaton", "BUR", "GKP" ],
  [ "Vokes", "BUR", "FWD" ],
  [ "Andre Gray", "BUR", "FWD" ],
  [ "Ben Mee", "BUR", "DEF" ],
  [ "Stephen Ward", "BUR", "DEF" ],
  [ "Lowton", "BUR", "DEF" ],
  [ "Ashley Barnes", "BUR", "FWD" ],
  [ "Hendrick", "BUR", "MID" ],
  [ "Walters", "BUR", "MID" ],
  [ "Arfield", "BUR", "MID" ],
  [ "Defour", "BUR", "MID" ],
  [ "Marney", "BUR", "MID" ],
  [ "Cork", "BUR", "MID" ],
  [ "Gudmundsson", "BUR", "MID" ],
  [ "Brady", "BUR", "MID" ],
  [ "Bardsley", "BUR", "DEF" ],
  [ "Tarkowski", "BUR", "DEF" ],
  [ "Ashley Westwood", "BUR", "MID" ],
  [ "Kevin Long", "BUR", "DEF" ],
  [ "Pope", "BUR", "GKP" ],
  [ "Charlie Taylor", "BUR", "DEF" ],
  
  [ "Eden Hazard", "CHE", "MID" ],
  [ "Diego Costa", "CHE", "FWD" ],
  [ "Gary Cahill", "CHE", "DEF" ],
  [ "Marcos Alonso", "CHE", "DEF" ],
  [ "Azpilicueta", "CHE", "DEF" ],
  [ "Pedro", "CHE", "MID" ],
  [ "Thibaut Courtois", "CHE", "GKP" ],
  [ "David Luiz", "CHE", "DEF" ],
  [ "Fàbregas", "CHE", "MID" ],
  [ "Willian", "CHE", "MID" ],
  [ "Victor Moses", "CHE", "DEF" ],
  [ "Kanté", "CHE", "MID" ],
  [ "Caballero", "CHE", "GKP" ],
  [ "Batshuayi", "CHE", "FWD" ],
  [ "Kenedy", "CHE", "MID" ],
  [ "Eduardo Carvalho", "CHE", "GKP" ],
  [ "Rüdiger", "CHE", "DEF" ],
  [ "Andreas Christensen", "CHE", "DEF" ],
  [ "Tiemoué Bakayoko", "CHE", "MID" ],
  [ "Charly Musonda", "CHE", "MID" ],
  [ "Álvaro Morata", "CHE", "FWD" ],
  
  [ "Zaha", "CRY", "MID" ],
  [ "Christian Benteke", "CRY", "FWD" ],
  [ "Townsend", "CRY", "MID" ],
  [ "van Aanholt", "CRY", "DEF" ],
  [ "McArthur", "CRY", "MID" ],
  [ "Hennessey", "CRY", "GKP" ],
  [ "Puncheon", "CRY", "MID" ],
  [ "Cabaye", "CRY", "MID" ],
  [ "Joel Ward", "CRY", "DEF" ],
  [ "Tomkins", "CRY", "DEF" ],
  [ "Scott Dann", "CRY", "DEF" ],
  [ "Damien Delaney", "CRY", "DEF" ],
  [ "Schlupp", "CRY", "DEF" ],
  [ "Martin Kelly", "CRY", "DEF" ],
  [ "Milivojevic", "CRY", "MID" ],
  [ "Lee Chung-yong", "CRY", "MID" ],
  [ "Wickham", "CRY", "FWD" ],
  [ "Sako", "CRY", "MID" ],
  [ "Souaré", "CRY", "DEF" ],
  [ "Loftus-Cheek", "CRY", "MID" ],
  [ "Speroni", "CRY", "GKP" ],
  [ "Jairo Riedewald", "CRY", "DEF" ],
  
  [ "Barkley", "EVE", "MID" ],
  [ "Baines", "EVE", "DEF" ],
  [ "Seamus Coleman", "EVE", "DEF" ],
  [ "Ashley Williams", "EVE", "DEF" ],
  [ "Mirallas", "EVE", "MID" ],
  [ "Michael Keane", "EVE", "DEF" ],
  [ "Jagielka", "EVE", "DEF" ],
  [ "Pickford", "EVE", "GKP" ],
  [ "Robles", "EVE", "GKP" ],
  [ "Idrissa Gueye", "EVE", "MID" ],
  [ "Wayne Rooney", "EVE", "FWD" ],
  [ "Funes Mori", "EVE", "DEF" ],
  [ "Stekelenburg", "EVE", "GKP" ],
  [ "Gareth Barry", "EVE", "MID" ],
  [ "Tom Davies", "EVE", "MID" ],
  [ "Holgate", "EVE", "DEF" ],
  [ "Bolasie", "EVE", "MID" ],
  [ "Schneiderlin", "EVE", "MID" ],
  [ "Martina", "EVE", "DEF" ],
  [ "James McCarthy", "EVE", "MID" ],
  [ "Lennon", "EVE", "MID" ],
  [ "Calvert-Lewin", "EVE", "FWD" ],
  [ "Lookman", "EVE", "MID" ],
  [ "Jonjoe Kenny", "EVE", "DEF" ],
  [ "Besic", "EVE", "MID" ],
  [ "Davy Klaassen", "EVE", "MID" ],
  [ "Sandro", "EVE", "FWD" ],
    
  [ "Vardy", "LEI", "FWD" ],
  [ "Mahrez", "LEI", "MID" ],
  [ "Kasper Schmeichel", "LEI", "GKP" ],
  [ "Fuchs", "LEI", "DEF" ],
  [ "Albrighton", "LEI", "MID" ],
  [ "Huth", "LEI", "DEF" ],
  [ "Jakupovic", "LEI", "GKP" ],
  [ "Danny Simpson", "LEI", "DEF" ],
  [ "Slimani", "LEI", "FWD" ],
  [ "Maguire", "LEI", "DEF" ],
  [ "Drinkwater", "LEI", "MID" ],
  [ "Wes Morgan", "LEI", "DEF" ],
  [ "Okazaki", "LEI", "FWD" ],
  [ "Ndidi", "LEI", "MID" ],
  [ "Demarai Gray", "LEI", "MID" ],
  [ "Amartey", "LEI", "MID" ],
  [ "Iheanacho", "LEI", "FWD" ],
  [ "Andy King", "LEI", "MID" ],
  [ "Ahmed Musa", "LEI", "MID" ],
  [ "Benalouane", "LEI", "DEF" ],
  [ "Ulloa", "LEI", "FWD" ],
  [ "Chilwell", "LEI", "DEF" ],
  [ "Nampalys Mendy", "LEI", "MID" ],
  [ "Matthew James", "LEI", "MID" ],
  [ "Hamer", "LEI", "GKP" ],
  [ "Molla Wagué", "LEI", "DEF" ],
  [ "Vicente Iborra", "LEI", "MID" ],
    
  [ "Firmino", "LIV", "FWD" ],
  [ "Coutinho", "LIV", "MID" ],
  [ "Sadio Mané", "LIV", "MID" ],
  [ "Wijnaldum", "LIV", "MID" ],
  [ "Milner", "LIV", "DEF" ],
  [ "Lallana", "LIV", "MID" ],
  [ "Clyne", "LIV", "DEF" ],
  [ "Mignolet", "LIV", "GKP" ],
  [ "Lovren", "LIV", "DEF" ],
  [ "Emre Can", "LIV", "MID" ],
  [ "Matip", "LIV", "DEF" ],
  [ "Origi", "LIV", "FWD" ],
  [ "Robertson", "LIV", "DEF" ],
  [ "Jordan Henderson", "LIV", "MID" ],
  [ "Daniel Sturridge", "LIV", "FWD" ],
  [ "Klavan", "LIV", "DEF" ],
  [ "Mamadou Sakho", "LIV", "DEF" ],
  [ "Karius", "LIV", "GKP" ],
  [ "Alberto Moreno", "LIV", "DEF" ],
  [ "Alexander-Arnold", "LIV", "DEF" ],
  [ "Woodburn", "LIV", "MID" ],
  [ "Grujic", "LIV", "MID" ],
  [ "Joseph Gomez", "LIV", "DEF" ],
  [ "Seyi Ojo", "LIV", "MID" ],
  [ "Mohamed Salah", "LIV", "MID" ],
  [ "Danny Ings", "LIV", "FWD" ],
  [ "Solanke", "LIV", "FWD" ],
  
  [ "De Bruyne", "MAC", "MID" ],
  [ "Agüero", "MAC", "FWD" ],
  [ "Sterling", "MAC", "MID" ],
  [ "Kyle Walker", "MAC", "DEF" ],
  [ "David Silva", "MAC", "MID" ],
  [ "Leroy Sané", "MAC", "MID" ],
  [ "Otamendi", "MAC", "DEF" ],
  [ "Yaya Touré", "MAC", "MID" ],
  [ "Fernandinho", "MAC", "MID" ],
  [ "Claudio Bravo", "MAC", "GKP" ],
  [ "Gabriel Jesus", "MAC", "FWD" ],
  [ "Stones", "MAC", "DEF" ],
  [ "Kompany", "MAC", "DEF" ],
  [ "Gündogan", "MAC", "MID" ],
  [ "Fernando Francisco Reges", "MAC", "MID" ],
  [ "Delph", "MAC", "MID" ],
  [ "Ederson", "MAC", "GKP" ],
  [ "Danilo", "MAC", "DEF" ],
  [ "Benjamin Mendy", "MAC", "DEF" ],
  [ "Bernardo Silva", "MAC", "MID" ],
  
  [ "Lukaku", "MAU", "FWD" ],
  [ "David de Gea", "MAU", "GKP" ],
  [ "Antonio Valencia", "MAU", "DEF" ],
  [ "Pogba", "MAU", "MID" ],
  [ "Bailly", "MAU", "DEF" ],
  [ "Matic", "MAU", "MID" ],
  [ "Mata", "MAU", "MID" ],
  [ "Blind", "MAU", "DEF" ],
  [ "Ander Herrera", "MAU", "MID" ],
  [ "Martial", "MAU", "MID" ],
  [ "Rojo", "MAU", "DEF" ],
  [ "Rashford", "MAU", "FWD" ],
  [ "Mkhitaryan", "MAU", "MID" ],
  [ "Darmian", "MAU", "DEF" ],
  [ "Lingard", "MAU", "MID" ],
  [ "Phil Jones", "MAU", "DEF" ],
  [ "Smalling", "MAU", "DEF" ],
  [ "Fellaini", "MAU", "MID" ],
  [ "Luke Shaw", "MAU", "DEF" ],
  [ "Carrick", "MAU", "MID" ],
  [ "Ashley Young", "MAU", "MID" ],
  [ "Romero", "MAU", "GKP" ],
  [ "Tuanzebe", "MAU", "DEF" ],
  [ "Fosu-Mensah", "MAU", "DEF" ],
  [ "Joel Pereira", "MAU", "GKP" ],
  [ "McTominay", "MAU", "MID" ],
  [ "Victor Lindelöf", "MAU", "DEF" ],
  [ "Andreas Pereira", "MAU", "MID" ],
  
  [ "Forster", "SOU", "GKP" ],
  [ "Nathan Redmond", "SOU", "MID" ],
  [ "Ryan Bertrand", "SOU", "DEF" ],
  [ "Tadic", "SOU", "MID" ],
  [ "Cédric Soares", "SOU", "DEF" ],
  [ "Ward-Prowse", "SOU", "MID" ],
  [ "Oriol Romeu", "SOU", "MID" ],
  [ "Yoshida", "SOU", "DEF" ],
  [ "Steven Davis", "SOU", "MID" ],
  [ "van Dijk", "SOU", "DEF" ],
  [ "Austin", "SOU", "FWD" ],
  [ "Jack Stephens", "SOU", "DEF" ],
  [ "Shane Long", "SOU", "FWD" ],
  [ "Boufal", "SOU", "MID" ],
  [ "Clasie", "SOU", "MID" ],
  [ "Højbjerg", "SOU", "MID" ],
  [ "Gabbiadini", "SOU", "FWD" ],
  [ "McQueen", "SOU", "DEF" ],
  [ "Targett", "SOU", "DEF" ],
  [ "Sims", "SOU", "MID" ],
  [ "Pied", "SOU", "DEF" ],
  [ "Alex McCarthy", "SOU", "GKP" ],
  [ "Jan Bednarek", "SOU", "DEF" ],
  
  [ "Dele Alli", "TOT", "MID" ],
  [ "Harry Kane", "TOT", "FWD" ],
  [ "Eriksen", "TOT", "MID" ],
  [ "Heung-Min Son", "TOT", "MID" ],
  [ "Lloris", "TOT", "GKP" ],
  [ "Vertonghen", "TOT", "DEF" ],
  [ "Alderweireld", "TOT", "DEF" ],
  [ "Wanyama", "TOT", "MID" ],
  [ "Eric Dier", "TOT", "MID" ],
  [ "Ben Davies", "TOT", "DEF" ],
  [ "Danny Rose", "TOT", "DEF" ],
  [ "Mousa Dembélé", "TOT", "MID" ],
  [ "Janssen", "TOT", "FWD" ],
  [ "Trippier", "TOT", "DEF" ],
  [ "Moussa Sissoko", "TOT", "MID" ],
  [ "Winks", "TOT", "MID" ],
  [ "Lamela", "TOT", "MID" ],
  [ "Vorm", "TOT", "GKP" ],
  [ "Nkoudou", "TOT", "MID" ],
  [ "Wimmer", "TOT", "DEF" ],
  
  [ "Allen", "STO", "MID" ],
  [ "Lee Grant", "STO", "GKP" ],
  [ "Pieters", "STO", "DEF" ],
  [ "Darren Fletcher", "STO", "MID" ],
  [ "Shawcross", "STO", "DEF" ],
  [ "Shaqiri", "STO", "MID" ],
  [ "Crouch", "STO", "FWD" ],
  [ "Charlie Adam", "STO", "MID" ],
  [ "Geoff Cameron", "STO", "DEF" ],
  [ "Glen Johnson", "STO", "DEF" ],
  [ "Mame Biram Diouf", "STO", "FWD" ],
  [ "Sobhi", "STO", "MID" ],
  [ "Muniesa", "STO", "DEF" ],
  [ "Bojan Krkic", "STO", "MID" ],
  [ "Berahino", "STO", "FWD" ],
  [ "Imbula", "STO", "MID" ],
  [ "Butland", "STO", "GKP" ],
  [ "Kurt Zouma", "STO", "DEF" ],
  [ "Afellay", "STO", "MID" ],
  [ "Tymon", "STO", "DEF" ],
  [ "Joselu", "STO", "FWD" ],
    
  [ "Gylfi Sigurdsson", "SWA", "MID" ],
  [ "Llorente", "SWA", "FWD" ],
  [ "Fabianski", "SWA", "GKP" ],
  [ "Leroy Fer", "SWA", "MID" ],
  [ "Mawson", "SWA", "DEF" ],
  [ "Kyle Naughton", "SWA", "DEF" ],
  [ "Wayne Routledge", "SWA", "MID" ],
  [ "Fernández", "SWA", "DEF" ],
  [ "Martin Olsson", "SWA", "DEF" ],
  [ "Tom Carroll", "SWA", "MID" ],
  [ "Ki Sung-yueng", "SWA", "MID" ],
  [ "Jordan Ayew", "SWA", "FWD" ],
  [ "Modou Barrow", "SWA", "MID" ],
  [ "Britton", "SWA", "MID" ],
  [ "Kingsley", "SWA", "DEF" ],
  [ "Rangel", "SWA", "DEF" ],
  [ "Narsingh", "SWA", "MID" ],
  [ "Jay Fulton", "SWA", "MID" ],
  [ "Montero", "SWA", "MID" ],
  [ "van der Hoorn", "SWA", "DEF" ],
  [ "Nathan Dyer", "SWA", "MID" ],
  [ "McBurnie", "SWA", "FWD" ],
  [ "Nordfeldt", "SWA", "GKP" ],
  [ "Bartley", "SWA", "DEF" ],
  [ "Roque Mesa", "SWA", "MID" ],
  [ "Abraham", "SWA", "FWD" ],
  
  [ "Capoue", "WAT", "MID" ],
  [ "Deeney", "WAT", "FWD" ],
  [ "Heurelho Gomes", "WAT", "GKP" ],
  [ "Holebas", "WAT", "DEF" ],
  [ "Britos", "WAT", "DEF" ],
  [ "Prödl", "WAT", "DEF" ],
  [ "Amrabat", "WAT", "MID" ],
  [ "Kaboul", "WAT", "DEF" ],
  [ "Cleverley", "WAT", "MID" ],
  [ "Janmaat", "WAT", "DEF" ],
  [ "Behrami", "WAT", "MID" ],
  [ "Pereyra", "WAT", "MID" ],
  [ "Okaka", "WAT", "FWD" ],
  [ "Doucouré", "WAT", "MID" ],
  [ "Kabasele", "WAT", "DEF" ],
  [ "Cathcart", "WAT", "DEF" ],
  [ "Success", "WAT", "MID" ],
  [ "Mariappa", "WAT", "DEF" ],
  [ "Chalobah", "WAT", "MID" ],
  [ "Zárate", "WAT", "FWD" ],
  [ "Pantilimon", "WAT", "GKP" ],
  [ "Brandon Mason", "WAT", "DEF" ],
  [ "Ben Watson", "WAT", "MID" ],
  [ "Kiko Femenía", "WAT", "DEF" ],
  [ "Will Hughes", "WAT", "MID" ],
  
  [ "McAuley", "WBA", "DEF" ],
  [ "Rondón", "WBA", "FWD" ],
  [ "Matt Phillips", "WBA", "MID" ],
  [ "Foster", "WBA", "GKP" ],
  [ "Chadli", "WBA", "MID" ],
  [ "Craig Dawson", "WBA", "DEF" ],
  [ "Brunt", "WBA", "MID" ],
  [ "James Morrison", "WBA", "MID" ],
  [ "Jonny Evans", "WBA", "DEF" ],
  [ "Livermore", "WBA", "MID" ],
  [ "Nyom", "WBA", "DEF" ],
  [ "Jay Rodriguez", "WBA", "FWD" ],
  [ "Yacob", "WBA", "MID" ],
  [ "McClean", "WBA", "MID" ],
  [ "Robson-Kanu", "WBA", "FWD" ],
  [ "Leko", "WBA", "MID" ],
  [ "Sam Field", "WBA", "MID" ],
  [ "Myhill", "WBA", "GKP" ],
  [ "Hegazi", "WBA", "DEF" ],
 
  [ "Snodgrass", "WES", "MID" ],
  [ "Lanzini", "WES", "MID" ],
  [ "Michail Antonio", "WES", "MID" ],
  [ "Arnautovic", "WES", "MID" ],
  [ "Winston Reid", "WES", "DEF" ],
  [ "Fonte", "WES", "DEF" ],
  [ "Andre Ayew", "WES", "MID" ],
  [ "Kouyaté", "WES", "MID" ],
  [ "Mark Noble", "WES", "MID" ],
  [ "James Collins", "WES", "DEF" ],
  [ "Andy Carroll", "WES", "FWD" ],
  [ "Adrián", "WES", "GKP" ],
  [ "Aaron Cresswell", "WES", "DEF" ],
  [ "Obiang", "WES", "MID" ],
  [ "Feghouli", "WES", "MID" ],
  [ "Ogbonna", "WES", "DEF" ],
  [ "Zabaleta", "WES", "DEF" ],
  [ "Edimilson Fernandes", "WES", "MID" ],
  [ "Masuaku", "WES", "DEF" ],
  [ "Byram", "WES", "DEF" ],
  [ "Diafra Sakho", "WES", "FWD" ],
  [ "Joe Hart", "WES", "GKP" ],
  [ "Javier Hernández", "WES", "FWD" ],
  
  [ "Manquillo", "NEW", "DEF" ],
  [ "Robert Elliot", "NEW", "GKP" ],
  [ "Darlow", "NEW", "GKP" ],
  [ "Yedlin", "NEW", "DEF" ],
  [ "Ciaran Clark", "NEW", "DEF" ],
  [ "Lascelles", "NEW", "DEF" ],
  [ "Dummett", "NEW", "DEF" ],
  [ "Grant Hanley", "NEW", "DEF" ],
  [ "Jesús Gámez", "NEW", "DEF" ],
  [ "Florian Lejeune", "NEW", "DEF" ],
  [ "Haidara", "NEW", "DEF" ],
  [ "Matt Ritchie", "NEW", "MID" ],
  [ "Shelvey", "NEW", "MID" ],
  [ "Diamé", "NEW", "MID" ],
  [ "Colback", "NEW", "MID" ],
  [ "Atsu", "NEW", "MID" ],
  [ "Siem de Jong", "NEW", "MID" ],
  [ "Aarons", "NEW", "MID" ],
  [ "Jacob Murphy", "NEW", "MID" ],
  [ "Gayle", "NEW", "FWD" ],
  [ "Ayoze Pérez", "NEW", "FWD" ],
  [ "Mitrovic", "NEW", "FWD" ],
 
  [ "Niki Mäenpää", "BRI", "GKP" ],
  [ "Mathew Ryan", "BRI", "GKP" ],
  [ "Lewis Dunk", "BRI", "DEF" ],
  [ "Shane Duffy", "BRI", "DEF" ],
  [ "Uwe Hünemeier", "BRI", "DEF" ],
  [ "Bruno", "BRI", "DEF" ],
  [ "Gaëtan Bong", "BRI", "DEF" ],
  [ "Liam Rosenior", "BRI", "DEF" ],
  [ "Connor Goldson", "BRI", "DEF" ],
  [ "Markus Suttner", "BRI", "DEF" ],
  [ "Anthony Knockaert", "BRI", "MID" ],
  [ "Dale Stephens", "BRI", "MID" ],
  [ "Beram Kayal", "BRI", "MID" ],
  [ "Steve Sidwell", "BRI", "MID" ],
  [ "Solomon March", "BRI", "MID" ],
  [ "Jiri Skalak", "BRI", "MID" ],
  [ "Jamie Murphy", "BRI", "MID" ],
  [ "Pascal Groß", "BRI", "MID" ],
  [ "Isaiah Brown", "BRI", "MID" ],
  [ "Glenn Murray", "BRI", "FWD" ],
  [ "Tomer Hemed", "BRI", "FWD" ],
  [ "Sam Baldock", "BRI", "FWD" ],
  
  [ "Joel Coleman", "HUD", "GKP" ],
  [ "Jonas Lössl", "HUD", "GKP" ],
  [ "Christopher Schindler", "HUD", "DEF" ],
  [ "Chris Löwe", "HUD", "DEF" ],
  [ "Tommy Smith", "HUD", "DEF" ],
  [ "Michael Hefele", "HUD", "DEF" ],
  [ "Martin Cranie", "HUD", "DEF" ],
  [ "Jon Gorenc Stankovic", "HUD", "DEF" ],
  [ "Mark Hudson", "HUD", "DEF" ],
  [ "Zanka", "HUD", "DEF" ],
  [ "Scott Malone", "HUD", "DEF" ],
  [ "Aaron Mooy", "HUD", "MID" ],
  [ "Rajiv van La Parra", "HUD", "MID" ],
  [ "Jonathan Hogg", "HUD", "MID" ],
  [ "Philip Billing", "HUD", "MID" ],
  [ "Joe Lolley", "HUD", "MID" ],
  [ "Dean Whitehead", "HUD", "MID" ],
  [ "Harry Bunn", "HUD", "MID" ],
  [ "Sean Scannell", "HUD", "MID" ],
  [ "Elias Kachunga", "HUD", "MID" ],
  [ "Tom Ince", "HUD", "MID" ],
  [ "Kasey Palmer", "HUD", "MID" ],
  [ "Danny Williams", "HUD", "MID" ],
  [ "Nahki Wells", "HUD", "FWD" ],
  [ "Collin Quaner", "HUD", "FWD" ],
  [ "Laurent Depoitre", "HUD", "FWD" ],
  [ "Steve Mounie", "HUD", "FWD" ],
  
]

puts("Seeding player season infos and stats...")

player_count = 0

players.each do | name, team_code, position_code |
  team = Team.where(code: team_code).first
  if team.nil? then
    puts "Could not find team with code #{team_code}"
  else
    position = nil
    if position_code == "GKP" then
      position = Position.find(1)
    elsif position_code == "DEF" then
      position = Position.find(3)
    elsif position_code == "MID" then
      position = Position.find(4)
    elsif position_code == "FWD" then
      position = Position.find(5)      
    end
    if position.nil? then
      puts "Could not find position with code #{position_code}"
    else    
      players = Player.named(name)
      player_size = players.size
      if player_size > 1 then
        players = Player.where(parameterized_name: name.parameterize)
      end
      if players.size != 1 then
        puts "Found #{player_size} players for name #{name}"
      else
        player_count += 1
        player = players.first
        player_season_info = PlayerSeasonInfo.where(season_id: 15, player: player).first
        if player_season_info.nil? then
          PlayerSeasonInfo.create(player_id: player.id, season_id: 15, team_id: team.id, d11_team_id: 1, position_id: position.id, value: 0)
        else
          player_season_info.team_id = team.id
          player_season_info.position_id = position.id
          player_season_info.save
        end
        player_season_stat = PlayerSeasonStat.where(season_id: 15, player: players.first).first
        if player_season_stat.nil? then
          PlayerSeasonStat.create(player_id: player.id, season_id: 15)
        end        
      end
    end
  end
end

puts "Total players #{player_count}, player_season_infos #{PlayerSeasonInfo.where(season_id: 15).size}, player_season_stats #{PlayerSeasonStat.where(season_id: 15).size}"

puts("Updating player rankings...")

PlayerSeasonStat.update_rankings(Season.find(15))


