players = [
  [ "AFC Bournemouth", "Artur Boruc" ],
  [ "AFC Bournemouth", "Asmir Begovic" ],
  [ "AFC Bournemouth", "Mark Travers" ],
  [ "AFC Bournemouth", "Aaron Ramsdale" ],
  [ "AFC Bournemouth", "Simon Francis" ],
  [ "AFC Bournemouth", "Steve Cook" ],
  [ "AFC Bournemouth", "Nathan Aké" ],
  [ "AFC Bournemouth", "Charlie Daniels" ],
  [ "AFC Bournemouth", "Adam Smith" ],
  [ "AFC Bournemouth", "Diego Rico" ],
  [ "AFC Bournemouth", "Jack Simpson" ],
  [ "AFC Bournemouth", "Chris Mepham" ],
  [ "AFC Bournemouth", "Brad Smith" ],
  [ "AFC Bournemouth", "Dan Gosling" ],
  [ "AFC Bournemouth", "Andrew Surman" ],
  [ "AFC Bournemouth", "Jefferson Lerma" ],
  [ "AFC Bournemouth", "Jordon Ibe" ],
  [ "AFC Bournemouth", "Lewis Cook" ],
  [ "AFC Bournemouth", "Junior Stanislas" ],
  [ "AFC Bournemouth", "David Brooks" ],
  [ "AFC Bournemouth", "Ryan Fraser" ],
  [ "AFC Bournemouth", "Kyle Taylor" ],
  [ "AFC Bournemouth", "Matt Butcher" ],
  [ "AFC Bournemouth", "Harry Arter" ],
  [ "AFC Bournemouth", "Mihai-Alexandru Dobre" ],
  [ "AFC Bournemouth", "Callum Wilson" ],
  [ "AFC Bournemouth", "Joshua King" ],
  [ "AFC Bournemouth", "Dominic Solanke" ],
  [ "AFC Bournemouth", "Sam Surridge" ],
  [ "Arsenal FC", "Bernd Leno" ],
  [ "Arsenal FC", "Emiliano Martínez" ],
  [ "Arsenal FC", "Matt Macey" ],
  [ "Arsenal FC", "Héctor Bellerín" ],
  [ "Arsenal FC", "Sokratis" ],
  [ "Arsenal FC", "Laurent Koscielny" ],
  [ "Arsenal FC", "Rob Holding" ],
  [ "Arsenal FC", "Nacho Monreal" ],
  [ "Arsenal FC", "Shkodran Mustafi" ],
  [ "Arsenal FC", "Carl Jenkinson" ],
  [ "Arsenal FC", "Konstantinos Mavropanos" ],
  [ "Arsenal FC", "Sead Kolasinac" ],
  [ "Arsenal FC", "Zech Medley" ],
  [ "Arsenal FC", "Calum Chambers" ],
  [ "Arsenal FC", "Mohamed Elneny" ],
  [ "Arsenal FC", "Henrikh Mkhitaryan" ],
  [ "Arsenal FC", "Mesut Özil" ],
  [ "Arsenal FC", "Lucas Torreira" ],
  [ "Arsenal FC", "Ainsley Maitland-Niles" ],
  [ "Arsenal FC", "Alex Iwobi" ],
  [ "Arsenal FC", "Matteo Guendouzi" ],
  [ "Arsenal FC", "Granit Xhaka" ],
  [ "Arsenal FC", "Joe Willock" ],
  [ "Arsenal FC", "Emile Smith Rowe" ],
  [ "Arsenal FC", "Alexandre Lacazette" ],
  [ "Arsenal FC", "Pierre-Emerick Aubameyang" ],
  [ "Arsenal FC", "Eddie Nketiah" ],
  [ "Arsenal FC", "Tyreece John-Jules" ],
  [ "Arsenal FC", "Bukayo Saka" ],
  [ "Arsenal FC", "Reiss Nelson" ],
  [ "Aston Villa", "Jed Steer" ],
  [ "Aston Villa", "Neil Taylor" ],
  [ "Aston Villa", "James Chester" ],
  [ "Aston Villa", "Matt Targett" ],
  [ "Aston Villa", "Kortney Hause" ],
  [ "Aston Villa", "Tyrone Mings" ],
  [ "Aston Villa", "Henri Lansbury" ],
  [ "Aston Villa", "Jack Grealish" ],
  [ "Aston Villa", "Keinan Davis" ],
  [ "Aston Villa", "Andre Green" ],
  [ "Aston Villa", "Rushian Hepburn-Murphy" ],
  [ "Brighton & Hove Albion", "Mat Ryan" ],
  [ "Brighton & Hove Albion", "Jason Steele" ],
  [ "Brighton & Hove Albion", "David Button" ],
  [ "Brighton & Hove Albion", "Robert Sánchez" ],
  [ "Brighton & Hove Albion", "Gaëtan Bong" ],
  [ "Brighton & Hove Albion", "Shane Duffy" ],
  [ "Brighton & Hove Albion", "Lewis Dunk" ],
  [ "Brighton & Hove Albion", "Leon Balogun" ],
  [ "Brighton & Hove Albion", "Martín Montoya" ],
  [ "Brighton & Hove Albion", "Dan Burn" ],
  [ "Brighton & Hove Albion", "Ezequiel Schelotto" ],
  [ "Brighton & Hove Albion", "Markus Suttner" ],
  [ "Brighton & Hove Albion", "Dale Stephens" ],
  [ "Brighton & Hove Albion", "Beram Kayal" ],
  [ "Brighton & Hove Albion", "Yves Bissouma" ],
  [ "Brighton & Hove Albion", "Anthony Knockaert" ],
  [ "Brighton & Hove Albion", "Pascal Groß" ],
  [ "Brighton & Hove Albion", "Solly March" ],
  [ "Brighton & Hove Albion", "Davy Pröpper" ],
  [ "Brighton & Hove Albion", "Max Sanders" ],
  [ "Brighton & Hove Albion", "Jayson Molumby" ],
  [ "Brighton & Hove Albion", "Jürgen Locadia" ],
  [ "Brighton & Hove Albion", "Florin Andone" ],
  [ "Brighton & Hove Albion", "Alireza Jahanbakhsh" ],
  [ "Brighton & Hove Albion", "Glenn Murray" ],
  [ "Brighton & Hove Albion", "José Izquierdo" ],
  [ "Brighton & Hove Albion", "Viktor Gyokeres" ],
  [ "Brighton & Hove Albion", "Tomer Hemed" ],
  [ "Brighton & Hove Albion", "Percy Tau" ],
  [ "Brighton & Hove Albion", "Aaron Connolly" ],
  [ "Brighton & Hove Albion", "Taylor Richards" ],
  [ "Burnley", "Tom Heaton" ],
  [ "Burnley", "Joe Hart" ],
  [ "Burnley", "Nick Pope" ],
  [ "Burnley", "Adam Legzdins" ],
  [ "Burnley", "Matthew Lowton" ],
  [ "Burnley", "Charlie Taylor" ],
  [ "Burnley", "James Tarkowski" ],
  [ "Burnley", "Ben Mee" ],
  [ "Burnley", "Ben Gibson" ],
  [ "Burnley", "Phil Bardsley" ],
  [ "Burnley", "Kevin Long" ],
  [ "Burnley", "Anthony Driscoll-Glennon" ],
  [ "Burnley", "Ali Koiki" ],
  [ "Burnley", "Erik Pieters" ],
  [ "Burnley", "Jack Cork" ],
  [ "Burnley", "Johann Gudmundsson" ],
  [ "Burnley", "Robbie Brady" ],
  [ "Burnley", "Jeff Hendrick" ],
  [ "Burnley", "Steven Defour" ],
  [ "Burnley", "Ashley Westwood" ],
  [ "Burnley", "Aaron Lennon" ],
  [ "Burnley", "Josh Benson" ],
  [ "Burnley", "Ashley Barnes" ],
  [ "Burnley", "Chris Wood" ],
  [ "Burnley", "Matej Vydra" ],
  [ "Burnley", "Dwight McNeil" ],
  [ "Burnley", "Daniel Agyei" ],
  [ "Burnley", "Nahki Wells" ],
  [ "Burnley", "Jay Rodriguez" ],
  [ "Chelsea FC", "Kepa Arrizabalaga" ],
  [ "Chelsea FC", "Willy Caballero" ],
  [ "Chelsea FC", "Jamie Cumming" ],
  [ "Chelsea FC", "Antonio Rüdiger" ],
  [ "Chelsea FC", "Marcos Alonso" ],
  [ "Chelsea FC", "Davide Zappacosta" ],
  [ "Chelsea FC", "Andreas Christensen" ],
  [ "Chelsea FC", "César Azpilicueta" ],
  [ "Chelsea FC", "David Luiz" ],
  [ "Chelsea FC", "Emerson" ],
  [ "Chelsea FC", "Ethan Ampadu" ],
  [ "Chelsea FC", "Marc Guehi" ],
  [ "Chelsea FC", "Reece James" ],
  [ "Chelsea FC", "Trevoh Chalobah" ],
  [ "Chelsea FC", "Michael Hector" ],
  [ "Chelsea FC", "Matt Miazga" ],
  [ "Chelsea FC", "Kurt Zouma" ],
  [ "Chelsea FC", "Fikayo Tomori" ],
  [ "Chelsea FC", "Jorginho" ],
  [ "Chelsea FC", "Daniel Drinkwater" ],
  [ "Chelsea FC", "N'Golo Kanté" ],
  [ "Chelsea FC", "Ross Barkley" ],
  [ "Chelsea FC", "Ruben Loftus-Cheek" ],
  [ "Chelsea FC", "George McEachran" ],
  [ "Chelsea FC", "Christian Pulisic" ],
  [ "Chelsea FC", "Kenedy" ],
  [ "Chelsea FC", "Lucas Piazon" ],
  [ "Chelsea FC", "Lewis Baker" ],
  [ "Chelsea FC", "Kasey Palmer" ],
  [ "Chelsea FC", "Dujon Sterling" ],
  [ "Chelsea FC", "Mateo Kovacic" ],
  [ "Chelsea FC", "Tiemoué Bakayoko" ],
  [ "Chelsea FC", "Olivier Giroud" ],
  [ "Chelsea FC", "Callum Hudson-Odoi" ],
  [ "Chelsea FC", "Willian" ],
  [ "Chelsea FC", "Tammy Abraham" ],
  [ "Chelsea FC", "Isaiah Brown" ],
  [ "Chelsea FC", "Michy Batshuayi" ],
  [ "Crystal Palace", "Wayne Hennessey" ],
  [ "Crystal Palace", "Vicente Guaita" ],
  [ "Crystal Palace", "Joe Tupper" ],
  [ "Crystal Palace", "Dion Henry" ],
  [ "Crystal Palace", "Stephen Henderson" ],
  [ "Crystal Palace", "Joel Ward" ],
  [ "Crystal Palace", "Patrick van Aanholt" ],
  [ "Crystal Palace", "James Tomkins" ],
  [ "Crystal Palace", "Scott Dann" ],
  [ "Crystal Palace", "Mamadou Sakho" ],
  [ "Crystal Palace", "Jeffrey Schlupp" ],
  [ "Crystal Palace", "Martin Kelly" ],
  [ "Crystal Palace", "Sam Woods" ],
  [ "Crystal Palace", "Jairo Riedewald" ],
  [ "Crystal Palace", "Nikola Tavares" ],
  [ "Crystal Palace", "Luka Milivojevic" ],
  [ "Crystal Palace", "Max Meyer" ],
  [ "Crystal Palace", "Cheikhou Kouyaté" ],
  [ "Crystal Palace", "Andros Townsend" ],
  [ "Crystal Palace", "James McArthur" ],
  [ "Crystal Palace", "Luke Dreher" ],
  [ "Crystal Palace", "Gio McGregor" ],
  [ "Crystal Palace", "Nya Kirby" ],
  [ "Crystal Palace", "Wilfried Zaha" ],
  [ "Crystal Palace", "Christian Benteke" ],
  [ "Crystal Palace", "Connor Wickham" ],
  [ "Crystal Palace", "Alexander Sørloth" ],
  [ "Everton FC", "Jordan Pickford" ],
  [ "Everton FC", "Maarten Stekelenburg" ],
  [ "Everton FC", "Jonas Lössl" ],
  [ "Everton FC", "Leighton Baines" ],
  [ "Everton FC", "Michael Keane" ],
  [ "Everton FC", "Lucas Digne" ],
  [ "Everton FC", "Yerry Mina" ],
  [ "Everton FC", "Seamus Coleman" ],
  [ "Everton FC", "Mason Holgate" ],
  [ "Everton FC", "Cuco Martina" ],
  [ "Everton FC", "Matthew Pennington" ],
  [ "Everton FC", "Gylfi Sigurdsson" ],
  [ "Everton FC", "James McCarthy" ],
  [ "Everton FC", "Idrissa Gueye" ],
  [ "Everton FC", "Morgan Schneiderlin" ],
  [ "Everton FC", "Tom Davies" ],
  [ "Everton FC", "André Gomes" ],
  [ "Everton FC", "Kevin Mirallas" ],
  [ "Everton FC", "Joe Williams" ],
  [ "Everton FC", "Beni Baningime" ],
  [ "Everton FC", "Muhamed Besic" ],
  [ "Everton FC", "Fabian Delph" ],
  [ "Everton FC", "Theo Walcott" ],
  [ "Everton FC", "Cenk Tosun" ],
  [ "Everton FC", "Dominic Calvert-Lewin" ],
  [ "Everton FC", "Richarlison" ],
  [ "Everton FC", "Ademola Lookman" ],
  [ "Everton FC", "Henry Onyekuru" ],
  [ "Everton FC", "Oumar Niasse" ],
  [ "Leicester City", "Kasper Schmeichel" ],
  [ "Leicester City", "Danny Ward" ],
  [ "Leicester City", "Eldin Jakupovic" ],
  [ "Leicester City", "Ben Chilwell" ],
  [ "Leicester City", "Çaglar Söyüncü" ],
  [ "Leicester City", "Wes Morgan" ],
  [ "Leicester City", "Jonny Evans" ],
  [ "Leicester City", "Ricardo Pereira" ],
  [ "Leicester City", "Harry Maguire" ],
  [ "Leicester City", "Christian Fuchs" ],
  [ "Leicester City", "Filip Benkovic" ],
  [ "Leicester City", "Josh Knight" ],
  [ "Leicester City", "Callum Elder" ],
  [ "Leicester City", "Demarai Gray" ],
  [ "Leicester City", "James Maddison" ],
  [ "Leicester City", "Marc Albrighton" ],
  [ "Leicester City", "Daniel Amartey" ],
  [ "Leicester City", "Harvey Barnes" ],
  [ "Leicester City", "Matty James" ],
  [ "Leicester City", "Nampalys Mendy" ],
  [ "Leicester City", "Wilfred Ndidi" ],
  [ "Leicester City", "Rachid Ghezzal" ],
  [ "Leicester City", "Hamza Choudhury" ],
  [ "Leicester City", "Adrien Silva" ],
  [ "Leicester City", "Bartosz Kapustka" ],
  [ "Leicester City", "Andy King" ],
  [ "Leicester City", "Youri Tielemans" ],
  [ "Leicester City", "Kelechi Iheanacho" ],
  [ "Leicester City", "Jamie Vardy" ],
  [ "Leicester City", "Islam Slimani" ],
  [ "Leicester City", "Fousseni Diabaté" ],
  [ "Leicester City", "Ayoze Pérez" ],
  [ "Leicester City", "George Thomas" ],
  [ "Leicester City", "Layton Ndukwu" ],
  [ "Liverpool FC", "Alisson" ],
  [ "Liverpool FC", "Simon Mignolet" ],
  [ "Liverpool FC", "Caoimhin Kelleher" ],
  [ "Liverpool FC", "Virgil van Dijk" ],
  [ "Liverpool FC", "Dejan Lovren" ],
  [ "Liverpool FC", "Joseph Gomez" ],
  [ "Liverpool FC", "Andrew Robertson" ],
  [ "Liverpool FC", "Joel Matip" ],
  [ "Liverpool FC", "Ki-Jana Hoever" ],
  [ "Liverpool FC", "Trent Alexander-Arnold" ],
  [ "Liverpool FC", "Nathaniel Clyne" ],
  [ "Liverpool FC", "George Johnston" ],
  [ "Liverpool FC", "Nathaniel Phillips" ],
  [ "Liverpool FC", "Fabinho" ],
  [ "Liverpool FC", "Georginio Wijnaldum" ],
  [ "Liverpool FC", "James Milner" ],
  [ "Liverpool FC", "Naby Keita" ],
  [ "Liverpool FC", "Jordan Henderson" ],
  [ "Liverpool FC", "Adam Lallana" ],
  [ "Liverpool FC", "Alex Oxlade-Chamberlain" ],
  [ "Liverpool FC", "Curtis Jones" ],
  [ "Liverpool FC", "Isaac Christie-Davies" ],
  [ "Liverpool FC", "Harry Wilson" ],
  [ "Liverpool FC", "Ryan Kent" ],
  [ "Liverpool FC", "Roberto Firmino" ],
  [ "Liverpool FC", "Sadio Mané" ],
  [ "Liverpool FC", "Mohamed Salah" ],
  [ "Liverpool FC", "Xherdan Shaqiri" ],
  [ "Liverpool FC", "Rhian Brewster" ],
  [ "Liverpool FC", "Divock Origi" ],
  [ "Liverpool FC", "Ben Woodburn" ],
  [ "Manchester City", "Claudio Bravo" ],
  [ "Manchester City", "Ederson" ],
  [ "Manchester City", "Daniel Grimshaw" ],
  [ "Manchester City", "Kyle Walker" ],
  [ "Manchester City", "Danilo" ],
  [ "Manchester City", "John Stones" ],
  [ "Manchester City", "Aymeric Laporte" ],
  [ "Manchester City", "Eliaquim Mangala" ],
  [ "Manchester City", "Benjamin Mendy" ],
  [ "Manchester City", "Nicolás Otamendi" ],
  [ "Manchester City", "Eric Garcia" ],
  [ "Manchester City", "Tosin Adarabioyo" ],
  [ "Manchester City", "Angeliño" ],
  [ "Manchester City", "Ilkay Gündogan" ],
  [ "Manchester City", "Kevin De Bruyne" ],
  [ "Manchester City", "Bernardo Silva" ],
  [ "Manchester City", "David Silva" ],
  [ "Manchester City", "Fernandinho" ],
  [ "Manchester City", "Riyad Mahrez" ],
  [ "Manchester City", "Oleksandr Zinchenko" ],
  [ "Manchester City", "Phil Foden" ],
  [ "Manchester City", "Felix Nmecha" ],
  [ "Manchester City", "Claudio Gomes" ],
  [ "Manchester City", "Adrián Bernabé" ],
  [ "Manchester City", "Luke Bolton" ],
  [ "Manchester City", "Rodrigo" ],
  [ "Manchester City", "Iker Pozo" ],
  [ "Manchester City", "Aleix García" ],
  [ "Manchester City", "Ian Carlo Poveda-Ocampo" ],
  [ "Manchester City", "Raheem Sterling" ],
  [ "Manchester City", "Sergio Agüero" ],
  [ "Manchester City", "Leroy Sané" ],
  [ "Manchester City", "Gabriel Jesus" ],
  [ "Manchester City", "Lukas Nmecha" ],
  [ "Manchester City", "Nabili Zoubdi Touaizi" ],
  [ "Manchester United", "David de Gea" ],
  [ "Manchester United", "Lee Grant" ],
  [ "Manchester United", "Sergio Romero" ],
  [ "Manchester United", "Matej Kovar" ],
  [ "Manchester United", "Joel Pereira" ],
  [ "Manchester United", "Victor Lindelöf" ],
  [ "Manchester United", "Eric Bailly" ],
  [ "Manchester United", "Phil Jones" ],
  [ "Manchester United", "Chris Smalling" ],
  [ "Manchester United", "Marcos Rojo" ],
  [ "Manchester United", "Ashley Young" ],
  [ "Manchester United", "Diogo Dalot" ],
  [ "Manchester United", "Luke Shaw" ],
  [ "Manchester United", "Matteo Darmian" ],
  [ "Manchester United", "Aaron Wan-Bissaka" ],
  [ "Manchester United", "Timothy Fosu-Mensah" ],
  [ "Manchester United", "Axel Tuanzebe" ],
  [ "Manchester United", "Paul Pogba" ],
  [ "Manchester United", "Juan Mata" ],
  [ "Manchester United", "Jesse Lingard" ],
  [ "Manchester United", "Andreas Pereira" ],
  [ "Manchester United", "Fred" ],
  [ "Manchester United", "Nemanja Matic" ],
  [ "Manchester United", "James Garner" ],
  [ "Manchester United", "Scott McTominay" ],
  [ "Manchester United", "Tahith Chong" ],
  [ "Manchester United", "Angel Gomes" ],
  [ "Manchester United", "Daniel James" ],
  [ "Manchester United", "Ethan Hamilton" ],
  [ "Manchester United", "Alexis Sánchez" ],
  [ "Manchester United", "Romelu Lukaku" ],
  [ "Manchester United", "Marcus Rashford" ],
  [ "Manchester United", "Anthony Martial" ],
  [ "Manchester United", "Mason Greenwood" ],
  [ "Newcastle United", "Robert Elliot" ],
  [ "Newcastle United", "Martin Dubravka" ],
  [ "Newcastle United", "Karl Darlow" ],
  [ "Newcastle United", "Nathan Harker" ],
  [ "Newcastle United", "Freddy Woodman" ],
  [ "Newcastle United", "Ciaran Clark" ],
  [ "Newcastle United", "Paul Dummett" ],
  [ "Newcastle United", "Fabian Schär" ],
  [ "Newcastle United", "Jamaal Lascelles" ],
  [ "Newcastle United", "Federico Fernández" ],
  [ "Newcastle United", "Javier Manquillo" ],
  [ "Newcastle United", "Florian Lejeune" ],
  [ "Newcastle United", "DeAndre Yedlin" ],
  [ "Newcastle United", "Lewis Cass" ],
  [ "Newcastle United", "Achraf Lazaar" ],
  [ "Newcastle United", "Jamie Sterry" ],
  [ "Newcastle United", "Ki Sung-yueng" ],
  [ "Newcastle United", "Jonjo Shelvey" ],
  [ "Newcastle United", "Matt Ritchie" ],
  [ "Newcastle United", "Isaac Hayden" ],
  [ "Newcastle United", "Miguel Almirón" ],
  [ "Newcastle United", "Christian Atsu" ],
  [ "Newcastle United", "Sean Longstaff" ],
  [ "Newcastle United", "Kelland Watts" ],
  [ "Newcastle United", "Jack Colback" ],
  [ "Newcastle United", "Jacob Murphy" ],
  [ "Newcastle United", "Rolando Aarons" ],
  [ "Newcastle United", "Henri Saivet" ],
  [ "Newcastle United", "Yoshinori Muto" ],
  [ "Norwich City", "Tim Krul" ],
  [ "Norwich City", "Timm Klose" ],
  [ "Norwich City", "Grant Hanley" ],
  [ "Norwich City", "James Husband" ],
  [ "Norwich City", "Sam Byram" ],
  [ "Norwich City", "Alexander Tettey" ],
  [ "Norwich City", "Louis Thompson" ],
  [ "Norwich City", "Patrick Roberts" ],
  [ "Sheffield United", "Simon Moore" ],
  [ "Sheffield United", "Enda Stevens" ],
  [ "Sheffield United", "Chris Basham" ],
  [ "Sheffield United", "John Egan" ],
  [ "Sheffield United", "Richard Stearman" ],
  [ "Sheffield United", "Phil Jagielka" ],
  [ "Sheffield United", "Oliver Norwood" ],
  [ "Sheffield United", "Samir Carruthers" ],
  [ "Sheffield United", "Ravel Morrison" ],
  [ "Sheffield United", "Billy Sharp" ],
  [ "Sheffield United", "Ched Evans" ],
  [ "Sheffield United", "Callum Robinson" ],
  [ "Sheffield United", "Lys Mousset" ],
  [ "Southampton FC", "Alex McCarthy" ],
  [ "Southampton FC", "Angus Gunn" ],
  [ "Southampton FC", "Harry Lewis" ],
  [ "Southampton FC", "Fraser Forster" ],
  [ "Southampton FC", "Maya Yoshida" ],
  [ "Southampton FC", "Jannik Vestergaard" ],
  [ "Southampton FC", "Jack Stephens" ],
  [ "Southampton FC", "Ryan Bertrand" ],
  [ "Southampton FC", "Jan Bednarek" ],
  [ "Southampton FC", "Yan Valery" ],
  [ "Southampton FC", "Kayne Ramsay" ],
  [ "Southampton FC", "Cédric Soares" ],
  [ "Southampton FC", "Wesley Hoedt" ],
  [ "Southampton FC", "Sam McQueen" ],
  [ "Southampton FC", "Mohamed Elyounoussi" ],
  [ "Southampton FC", "Oriol Romeu" ],
  [ "Southampton FC", "James Ward-Prowse" ],
  [ "Southampton FC", "Stuart Armstrong" ],
  [ "Southampton FC", "Mario Lemina" ],
  [ "Southampton FC", "Nathan Redmond" ],
  [ "Southampton FC", "Pierre-Emile Højbjerg" ],
  [ "Southampton FC", "Josh Sims" ],
  [ "Southampton FC", "Tyreke Johnson" ],
  [ "Southampton FC", "Callum Slattery" ],
  [ "Southampton FC", "Jordy Clasie" ],
  [ "Southampton FC", "Sofiane Boufal" ],
  [ "Southampton FC", "Harrison Reed" ],
  [ "Southampton FC", "Shane Long" ],
  [ "Southampton FC", "Charlie Austin" ],
  [ "Southampton FC", "Michael Obafemi" ],
  [ "Southampton FC", "Marcus Barnes" ],
  [ "Southampton FC", "Guido Carrillo" ],
  [ "Southampton FC", "Danny Ings" ],
  [ "Tottenham Hotspur", "Hugo Lloris" ],
  [ "Tottenham Hotspur", "Paulo Gazzaniga" ],
  [ "Tottenham Hotspur", "Alfie Whiteman" ],
  [ "Tottenham Hotspur", "Danny Rose" ],
  [ "Tottenham Hotspur", "Toby Alderweireld" ],
  [ "Tottenham Hotspur", "Jan Vertonghen" ],
  [ "Tottenham Hotspur", "Davinson Sánchez" ],
  [ "Tottenham Hotspur", "Kyle Walker-Peters" ],
  [ "Tottenham Hotspur", "Juan Foyth" ],
  [ "Tottenham Hotspur", "Serge Aurier" ],
  [ "Tottenham Hotspur", "Ben Davies" ],
  [ "Tottenham Hotspur", "Timothy Eyoma" ],
  [ "Tottenham Hotspur", "Japhet Tanganga" ],
  [ "Tottenham Hotspur", "Harry Winks" ],
  [ "Tottenham Hotspur", "Erik Lamela" ],
  [ "Tottenham Hotspur", "Victor Wanyama" ],
  [ "Tottenham Hotspur", "Eric Dier" ],
  [ "Tottenham Hotspur", "Moussa Sissoko" ],
  [ "Tottenham Hotspur", "Dele Alli" ],
  [ "Tottenham Hotspur", "Christian Eriksen" ],
  [ "Tottenham Hotspur", "Lucas Moura" ],
  [ "Tottenham Hotspur", "George Marsh" ],
  [ "Tottenham Hotspur", "Oliver Skipp" ],
  [ "Tottenham Hotspur", "Georges-Kévin Nkoudou" ],
  [ "Tottenham Hotspur", "Josh Onomah" ],
  [ "Tottenham Hotspur", "Anthony Georgiou" ],
  [ "Tottenham Hotspur", "Jamie Bowden" ],
  [ "Tottenham Hotspur", "Son Heung-Min" ],
  [ "Tottenham Hotspur", "Vincent Janssen" ],
  [ "Tottenham Hotspur", "Harry Kane" ],
  [ "Tottenham Hotspur", "Kazaiah Sterling" ],
  [ "Watford FC", "Ben Foster" ],
  [ "Watford FC", "Pontus Dahlberg" ],
  [ "Watford FC", "Daniel Bachmann" ],
  [ "Watford FC", "Daryl Janmaat" ],
  [ "Watford FC", "Sebastian Prödl" ],
  [ "Watford FC", "Adrian Mariappa" ],
  [ "Watford FC", "Adam Masina" ],
  [ "Watford FC", "Craig Cathcart" ],
  [ "Watford FC", "Kiko Femenía" ],
  [ "Watford FC", "Marc Navarro" ],
  [ "Watford FC", "José Holebas" ],
  [ "Watford FC", "Christian Kabasele" ],
  [ "Watford FC", "Dimitri Foulquier" ],
  [ "Watford FC", "Marvin Zeegelaar" ],
  [ "Watford FC", "Ben Wilmot" ],
  [ "Watford FC", "Craig Dawson" ],
  [ "Watford FC", "Tom Cleverley" ],
  [ "Watford FC", "Ken Sema" ],
  [ "Watford FC", "Nathaniel Chalobah" ],
  [ "Watford FC", "Abdoulaye Doucouré" ],
  [ "Watford FC", "Will Hughes" ],
  [ "Watford FC", "Domingos Quina" ],
  [ "Watford FC", "Etienne Capoue" ],
  [ "Watford FC", "Roberto Pereyra" ],
  [ "Watford FC", "Dodi Lukebakio" ],
  [ "Watford FC", "Gerard Deulofeu" ],
  [ "Watford FC", "Troy Deeney" ],
  [ "Watford FC", "Isaac Success" ],
  [ "Watford FC", "Adalberto Peñaranda" ],
  [ "Watford FC", "Andre Gray" ],
  [ "Watford FC", "Stefano Okaka" ],
  [ "West Ham United", "Lukasz Fabianski" ],
  [ "West Ham United", "Winston Reid" ],
  [ "West Ham United", "Aaron Cresswell" ],
  [ "West Ham United", "Fabián Balbuena" ],
  [ "West Ham United", "Pablo Zabaleta" ],
  [ "West Ham United", "Angelo Ogbonna" ],
  [ "West Ham United", "Issa Diop" ],
  [ "West Ham United", "Ryan Fredericks" ],
  [ "West Ham United", "Arthur Masuaku" ],
  [ "West Ham United", "Reece Oxford" ],
  [ "West Ham United", "Felipe Anderson" ],
  [ "West Ham United", "Manuel Lanzini" ],
  [ "West Ham United", "Robert Snodgrass" ],
  [ "West Ham United", "Pedro Obiang" ],
  [ "West Ham United", "Carlos Sánchez" ],
  [ "West Ham United", "Mark Noble" ],
  [ "West Ham United", "Jack Wilshere" ],
  [ "West Ham United", "Michail Antonio" ],
  [ "West Ham United", "Nathan Holland" ],
  [ "West Ham United", "Declan Rice" ],
  [ "West Ham United", "Grady Diangana" ],
  [ "West Ham United", "Ben Johnson" ],
  [ "West Ham United", "Conor Coventry" ],
  [ "West Ham United", "Josh Cullen" ],
  [ "West Ham United", "Joe Powell" ],
  [ "West Ham United", "Chicharito" ],
  [ "West Ham United", "Andriy Yarmolenko" ],
  [ "West Ham United", "Xande Silva" ],
  [ "West Ham United", "Jordan Hugill" ],
  [ "Wolverhampton Wanderers", "Rui Patrício" ],
  [ "Wolverhampton Wanderers", "John Ruddy" ],
  [ "Wolverhampton Wanderers", "Will Norris" ],
  [ "Wolverhampton Wanderers", "Matt Doherty" ],
  [ "Wolverhampton Wanderers", "Ryan Bennett" ],
  [ "Wolverhampton Wanderers", "Willy Boly" ],
  [ "Wolverhampton Wanderers", "Conor Coady" ],
  [ "Wolverhampton Wanderers", "Jonny" ],
  [ "Wolverhampton Wanderers", "Rúben Vinagre" ],
  [ "Wolverhampton Wanderers", "Cameron John" ],
  [ "Wolverhampton Wanderers", "Max Kilman" ],
  [ "Wolverhampton Wanderers", "Roderick Miranda" ],
  [ "Wolverhampton Wanderers", "Rúben Neves" ],
  [ "Wolverhampton Wanderers", "Morgan Gibbs-White" ],
  [ "Wolverhampton Wanderers", "Diogo Jota" ],
  [ "Wolverhampton Wanderers", "Elliot Watt" ],
  [ "Wolverhampton Wanderers", "Romain Saïss" ],
  [ "Wolverhampton Wanderers", "João Moutinho" ],
  [ "Wolverhampton Wanderers", "Leander Dendoncker" ],
  [ "Wolverhampton Wanderers", "Adama Traoré" ],
  [ "Wolverhampton Wanderers", "Rafa Mir" ],
  [ "Wolverhampton Wanderers", "Bright Enobakhare" ],
  [ "Wolverhampton Wanderers", "Léo Bonatini" ],
  [ "Wolverhampton Wanderers", "Raúl Jiménez" ],
]

players.each do |team_name, player_name|
  team = Team.where(name: team_name).first
  Player.named(player_name).each do |player|
    if player.name == player_name
      position = Position.find(6)
      player_season_infos = PlayerSeasonInfo.by_player(player)
      if player_season_infos.any?
        position = player_season_infos.first.position

        puts "Inserting player #{player.name}, position #{position.name}, team #{team.name}"
        PlayerSeasonInfo.create(player: player, season: Season.current, team: team, position: position)
        if !PlayerSeasonStat.where(player: player, season: Season.current).any? then
          PlayerSeasonStat.create(player: player, season: Season.current)
        end
      end
    end
  end
end
