players = [
  [ 'Aston Villa', 'ADDED', 'James Bree' ],
  [ 'Aston Villa', 'REMOVED', 'Jonathan Kodjia' ],
  [ 'Aston Villa', 'REMOVED', 'James Chester' ],
  [ 'Aston Villa', 'REMOVED', 'Aaron Tshibola' ],
  [ 'Aston Villa', 'REMOVED', 'Callum Hare' ],
  [ 'Aston Villa', 'REMOVED', 'Daniel Drinkwater' ],
  [ 'Aston Villa', 'REMOVED', 'José Reina' ],
  [ 'Aston Villa', 'REMOVED', 'Borja Bastón' ],
  [ 'Aston Villa', 'REMOVED', 'Kaine Hayden' ],
  [ 'Brighton & Hove Albion', 'ADDED', 'Christian Walton' ],
  [ 'Brighton & Hove Albion', 'ADDED', 'Robert Sánchez' ],
  [ 'Brighton & Hove Albion', 'ADDED', 'Ben White' ],
  [ 'Brighton & Hove Albion', 'ADDED', 'Joël Veltman' ],
  [ 'Brighton & Hove Albion', 'ADDED', 'Adam Lallana' ],
  [ 'Brighton & Hove Albion', 'ADDED', 'Max Sanders' ],
  [ 'Brighton & Hove Albion', 'ADDED', 'Jayson Molumby' ],
  [ 'Brighton & Hove Albion', 'ADDED', 'Jan Mlakar' ],
  [ 'Brighton & Hove Albion', 'ADDED', 'Viktor Gyökeres' ],
  [ 'Brighton & Hove Albion', 'REMOVED', 'Leon Balogun' ],
  [ 'Brighton & Hove Albion', 'REMOVED', 'Gaëtan Bong' ],
  [ 'Brighton & Hove Albion', 'REMOVED', 'Ezequiel Schelotto' ],
  [ 'Brighton & Hove Albion', 'REMOVED', 'Aaron Mooy' ],
  [ 'Brighton & Hove Albion', 'REMOVED', 'Jürgen Locadia' ],
  [ 'Brighton & Hove Albion', 'REMOVED', 'Tomer Hemed' ],
  [ 'Brighton & Hove Albion', 'REMOVED', 'Martín Montoya' ],
  [ 'Brighton & Hove Albion', 'REMOVED', 'Alex Cochrane' ],
  [ 'Burnley', 'ADDED', 'Will Norris' ],
  [ 'Burnley', 'ADDED', 'Aiden Neill' ],
  [ 'Burnley', 'REMOVED', 'Joel Senior' ],
  [ 'Burnley', 'REMOVED', 'Jimmy Dunne' ],
  [ 'Burnley', 'REMOVED', 'Joe Hart' ],
  [ 'Burnley', 'REMOVED', 'Adam Legzdins' ],
  [ 'Burnley', 'REMOVED', 'Steven Defour' ],
  [ 'Burnley', 'REMOVED', 'Aaron Lennon' ],
  [ 'Burnley', 'REMOVED', 'Jeff Hendrick' ],
  [ 'Burnley', 'REMOVED', 'Anthony Driscoll-Glennon' ],
  [ 'Burnley', 'REMOVED', 'Josh Benson' ],
  [ 'Burnley', 'REMOVED', 'Ali Koiki' ],
  [ 'Burnley', 'REMOVED', 'Mace Goodridge' ],
  [ 'Burnley', 'REMOVED', 'Bobby Thomas' ],
  [ 'Burnley', 'REMOVED', 'Max Thompson' ],
  [ 'Burnley', 'REMOVED', 'Lukas Jensen' ],
  [ 'Burnley', 'REMOVED', 'Joel Mumbongo' ],
  [ 'Chelsea', 'ADDED', 'Nathan Baxter' ],
  [ 'Chelsea', 'ADDED', 'Matt Miazga' ],
  [ 'Chelsea', 'ADDED', 'Ben Chilwell' ],
  [ 'Chelsea', 'ADDED', 'Malang Sarr' ],
  [ 'Chelsea', 'ADDED', 'Thiago Silva' ],
  [ 'Chelsea', 'ADDED', 'Juan Castillo' ],
  [ 'Chelsea', 'ADDED', 'Jake Clarke-Salter' ],
  [ 'Chelsea', 'ADDED', 'Ethan Ampadu' ],
  [ 'Chelsea', 'ADDED', 'Ian Maatsen' ],
  [ 'Chelsea', 'ADDED', 'Victor Moses' ],
  [ 'Chelsea', 'ADDED', 'Hakim Ziyech' ],
  [ 'Chelsea', 'ADDED', 'Daniel Drinkwater' ],
  [ 'Chelsea', 'ADDED', 'Henry Lawrence' ],
  [ 'Chelsea', 'ADDED', 'Conor Gallagher' ],
  [ 'Chelsea', 'ADDED', 'Harvey Vale' ],
  [ 'Chelsea', 'ADDED', 'Myles Peart-Harris' ],
  [ 'Chelsea', 'ADDED', 'Luke McCormick' ],
  [ 'Chelsea', 'ADDED', 'Lewis Baker' ],
  [ 'Chelsea', 'ADDED', 'Mario Pasalic' ],
  [ 'Chelsea', 'ADDED', 'Timo Werner' ],
  [ 'Chelsea', 'REMOVED', 'Jamie Cumming' ],
  [ 'Chelsea', 'REMOVED', 'Isaiah Brown' ],
  [ 'Chelsea', 'REMOVED', 'Marc Guehi' ],
  [ 'Chelsea', 'REMOVED', 'Pedro' ],
  [ 'Chelsea', 'REMOVED', 'Willian' ],
  [ 'Chelsea', 'REMOVED', 'Marco van Ginkel' ],
  [ 'Chelsea', 'REMOVED', 'Faustino Anjorin' ],
  [ 'Chelsea', 'REMOVED', 'Armando Broja' ],
  [ 'Chelsea', 'REMOVED', 'Lewis Bate' ],
  [ 'Crystal Palace', 'ADDED', 'Nathan Ferguson' ],
  [ 'Crystal Palace', 'ADDED', 'Eberechi Eze' ],
  [ 'Crystal Palace', 'REMOVED', 'Cenk Tosun' ],
  [ 'Crystal Palace', 'REMOVED', 'Stephen Henderson' ],
  [ 'Crystal Palace', 'REMOVED', 'Ryan Inniss' ],
  [ 'Crystal Palace', 'REMOVED', 'Victor Camarasa' ],
  [ 'Crystal Palace', 'REMOVED', 'Sam Woods' ],
  [ 'Crystal Palace', 'REMOVED', 'Nya Kirby' ],
  [ 'Crystal Palace', 'REMOVED', 'Nikola Tavares' ],
  [ 'Crystal Palace', 'REMOVED', 'Tyrick Mitchell' ],
  [ 'Crystal Palace', 'REMOVED', 'Brandon Pierrick' ],
  [ 'Crystal Palace', 'REMOVED', 'James Daly' ],
  [ 'Crystal Palace', 'REMOVED', 'Gio McGregor' ],
  [ 'Crystal Palace', 'REMOVED', 'John-Kymani Gordon' ],
  [ 'Everton', 'ADDED', 'Jonjoe Kenny' ],
  [ 'Everton', 'ADDED', 'Sandro Ramírez' ],
  [ 'Everton', 'ADDED', 'Cenk Tosun' ],
  [ 'Everton', 'REMOVED', 'Maarten Stekelenburg' ],
  [ 'Everton', 'REMOVED', 'Leighton Baines' ],
  [ 'Everton', 'REMOVED', 'Cuco Martina' ],
  [ 'Everton', 'REMOVED', 'Djibril Sidibe' ],
  [ 'Everton', 'REMOVED', 'Morgan Schneiderlin' ],
  [ 'Everton', 'REMOVED', 'Kevin Mirallas' ],
  [ 'Everton', 'REMOVED', 'Oumar Niasse' ],
  [ 'Everton', 'REMOVED', 'Lewis Gibson' ],
  [ 'Everton', 'REMOVED', 'Ellis Simms' ],
  [ 'Fulham', 'ADDED', 'Marcus Bettinelli' ],
  [ 'Fulham', 'ADDED', 'Marek Rodák' ],
  [ 'Fulham', 'ADDED', 'Jordan Archer' ],
  [ 'Fulham', 'ADDED', 'Fabri' ],
  [ 'Fulham', 'ADDED', 'Michael Hector' ],
  [ 'Fulham', 'ADDED', 'Denis Odoi' ],
  [ 'Fulham', 'ADDED', 'Alfie Mawson' ],
  [ 'Fulham', 'ADDED', 'Tim Ream' ],
  [ 'Fulham', 'ADDED', 'Maxime Le Marchand' ],
  [ 'Fulham', 'ADDED', 'Cyrus Christie' ],
  [ 'Fulham', 'ADDED', 'Joe Bryan' ],
  [ 'Fulham', 'ADDED', 'Steven Sessegnon' ],
  [ 'Fulham', 'ADDED', 'Antonee Robinson' ],
  [ 'Fulham', 'ADDED', 'Jean Michael Seri' ],
  [ 'Fulham', 'ADDED', 'Kevin McDonald' ],
  [ 'Fulham', 'ADDED', 'Neeskens Kebano' ],
  [ 'Fulham', 'ADDED', 'Stefan Johansen' ],
  [ 'Fulham', 'ADDED', 'Tom Cairney' ],
  [ 'Fulham', 'ADDED', 'Josh Onomah' ],
  [ 'Fulham', 'ADDED', 'André-Frank Zambo Anguissa' ],
  [ 'Fulham', 'ADDED', 'Mario Lemina' ],
  [ 'Fulham', 'ADDED', 'Harrison Reed' ],
  [ 'Fulham', 'ADDED', 'Aleksandar Mitrovic' ],
  [ 'Fulham', 'ADDED', 'Bobby De Cordova-Reid' ],
  [ 'Fulham', 'ADDED', 'Ivan Cavaleiro' ],
  [ 'Fulham', 'ADDED', 'Aboubakar Kamara' ],
  [ 'Leeds United', 'ADDED', 'Kiko Casilla' ],
  [ 'Leeds United', 'ADDED', 'Luke Ayling' ],
  [ 'Leeds United', 'ADDED', 'Barry Douglas' ],
  [ 'Leeds United', 'ADDED', 'Liam Cooper' ],
  [ 'Leeds United', 'ADDED', 'Gaetano Berardi' ],
  [ 'Leeds United', 'ADDED', 'Pascal Struijk' ],
  [ 'Leeds United', 'ADDED', 'Robbie Gotts' ],
  [ 'Leeds United', 'ADDED', 'Leif Davis' ],
  [ 'Leeds United', 'ADDED', 'Robin Koch' ],
  [ 'Leeds United', 'ADDED', 'Adam Forshaw' ],
  [ 'Leeds United', 'ADDED', 'Ezgjan Alioski' ],
  [ 'Leeds United', 'ADDED', 'Stuart Dallas' ],
  [ 'Leeds United', 'ADDED', 'Pablo Hernández' ],
  [ 'Leeds United', 'ADDED', 'Kalvin Phillips' ],
  [ 'Leeds United', 'ADDED', 'Mateusz Klich' ],
  [ 'Leeds United', 'ADDED', 'Jamie Shackleton' ],
  [ 'Leeds United', 'ADDED', 'Jack Harrison' ],
  [ 'Leeds United', 'ADDED', 'Jay-Roy Grot' ],
  [ 'Leeds United', 'ADDED', 'Ian Poveda-Ocampo' ],
  [ 'Leeds United', 'ADDED', 'Patrick Bamford' ],
  [ 'Leeds United', 'ADDED', 'Tyler Roberts' ],
  [ 'Leeds United', 'ADDED', 'Joe Gelhardt' ],
  [ 'Leeds United', 'ADDED', 'Rodrigo Moreno' ],
  [ 'Leicester City', 'ADDED', 'Vontae Daley-Campbell' ],
  [ 'Leicester City', 'ADDED', 'Josh Knight' ],
  [ 'Leicester City', 'ADDED', 'Sidnei Tavares' ],
  [ 'Leicester City', 'ADDED', 'Kiernan Dewsbury-Hall' ],
  [ 'Leicester City', 'ADDED', 'Thakgalo Leshabela' ],
  [ 'Leicester City', 'ADDED', 'Admiral Muskwe' ],
  [ 'Leicester City', 'ADDED', 'Josh Felix-Eppiah' ],
  [ 'Leicester City', 'REMOVED', 'Ben Chilwell' ],
  [ 'Leicester City', 'REMOVED', 'Ryan Bennett' ],
  [ 'Liverpool', 'ADDED', 'Loris Karius' ],
  [ 'Liverpool', 'ADDED', 'Kamil Grabara' ],
  [ 'Liverpool', 'ADDED', 'Konstantinos Tsimikas' ],
  [ 'Liverpool', 'ADDED', 'Billy Koumetio' ],
  [ 'Liverpool', 'ADDED', 'Marko Grujic' ],
  [ 'Liverpool', 'ADDED', 'Harry Wilson' ],
  [ 'Liverpool', 'ADDED', 'Sheyi Ojo' ],
  [ 'Liverpool', 'ADDED', 'Ben Woodburn' ],
  [ 'Liverpool', 'ADDED', 'Taiwo Awoniyi' ],
  [ 'Liverpool', 'REMOVED', 'Andy Lonergan' ],
  [ 'Liverpool', 'REMOVED', 'Nathaniel Clyne' ],
  [ 'Liverpool', 'REMOVED', 'Adam Lallana' ],
  [ 'Liverpool', 'REMOVED', 'Allan Souza' ],
  [ 'Liverpool', 'REMOVED', 'Ryan Kent' ],
  [ 'Liverpool', 'REMOVED', 'Dejan Lovren' ],
  [ 'Liverpool', 'REMOVED', 'Pedro Chirivella' ],
  [ 'Manchester City', 'ADDED', 'Arijanet Muric' ],
  [ 'Manchester City', 'ADDED', 'Nathan Aké' ],
  [ 'Manchester City', 'ADDED', 'Patrick Roberts' ],
  [ 'Manchester City', 'ADDED', 'Adrián Bernabé' ],
  [ 'Manchester City', 'ADDED', 'Ferran Torres' ],
  [ 'Manchester City', 'REMOVED', 'Daniel Grimshaw' ],
  [ 'Manchester City', 'REMOVED', 'Claudio Bravo' ],
  [ 'Manchester City', 'REMOVED', 'Leroy Sané' ],
  [ 'Manchester City', 'REMOVED', 'David Silva' ],
  [ 'Manchester United', 'ADDED', 'Dean Henderson' ],
  [ 'Manchester United', 'ADDED', 'Ethan Laird' ],
  [ 'Manchester United', 'ADDED', 'Teden Mengi' ],
  [ 'Manchester United', 'ADDED', 'Ethan Galbraith' ],
  [ 'Manchester United', 'REMOVED', 'Matteo Darmian' ],
  [ 'Manchester United', 'REMOVED', 'Alexis Sánchez' ],
  [ 'Manchester United', 'REMOVED', 'Ashley Young' ],
  [ 'Manchester United', 'REMOVED', 'Angel Gomes' ],
  [ 'Manchester United', 'REMOVED', 'Tahith Chong' ],
  [ 'Newcastle United', 'ADDED', 'Mark Gillespie' ],
  [ 'Newcastle United', 'ADDED', 'Jacob Murphy' ],
  [ 'Newcastle United', 'ADDED', 'Rolando Aarons' ],
  [ 'Newcastle United', 'ADDED', 'Jeff Hendrick' ],
  [ 'Newcastle United', 'REMOVED', 'Jetro Willems' ],
  [ 'Newcastle United', 'REMOVED', 'Robert Elliot' ],
  [ 'Newcastle United', 'REMOVED', 'Ki Sung-Yueng' ],
  [ 'Newcastle United', 'REMOVED', 'Danny Rose' ],
  [ 'Newcastle United', 'REMOVED', 'Thomas Allan' ],
  [ 'Newcastle United', 'REMOVED', 'Kelland Watts' ],
  [ 'Newcastle United', 'REMOVED', 'Liam Gibson' ],
  [ 'Newcastle United', 'REMOVED', 'Valentino Lazaro' ],
  [ 'Newcastle United', 'REMOVED', 'Nabil Bentaleb' ],
  [ 'Newcastle United', 'REMOVED', 'Jack Young' ],
  [ 'Sheffield United', 'ADDED', 'Wes Foderingham' ],
  [ 'Sheffield United', 'ADDED', 'Aaron Ramsdale' ],
  [ 'Sheffield United', 'REMOVED', 'Dean Henderson' ],
  [ 'Sheffield United', 'REMOVED', 'Kieron Freeman' ],
  [ 'Sheffield United', 'REMOVED', 'Leon Clarke' ],
  [ 'Sheffield United', 'REMOVED', 'Luke Freeman' ],
  [ 'Sheffield United', 'REMOVED', 'Muhamed Besic' ],
  [ 'Sheffield United', 'REMOVED', 'Richard Stearman' ],
  [ 'Sheffield United', 'REMOVED', 'Ravel Morrison' ],
  [ 'Sheffield United', 'REMOVED', 'Mark Duffy' ],
  [ 'Sheffield United', 'REMOVED', 'Jake Eastwood' ],
  [ 'Sheffield United', 'REMOVED', 'Panagiotis Retsos' ],
  [ 'Sheffield United', 'REMOVED', 'Richairo Zivkovic' ],
  [ 'Southampton', 'ADDED', 'Mohammed Salisu' ],
  [ 'Southampton', 'REMOVED', 'Wesley Hoedt' ],
  [ 'Southampton', 'REMOVED', 'Kayne Ramsay' ],
  [ 'Southampton', 'REMOVED', 'Callum Slattery' ],
  [ 'Southampton', 'REMOVED', 'Mohamed Elyounoussi' ],
  [ 'Southampton', 'REMOVED', 'Guido Carrillo' ],
  [ 'Southampton', 'REMOVED', 'Pierre-Emile Højbjerg' ],
  [ 'Southampton', 'REMOVED', 'Mario Lemina' ],
  [ 'Southampton', 'REMOVED', 'Maya Yoshida' ],
  [ 'Southampton', 'REMOVED', 'Kevin Danso' ],
  [ 'Southampton', 'REMOVED', 'Daniel Lundulu' ],
  [ 'Southampton', 'REMOVED', 'Sam McQueen' ],
  [ 'Southampton', 'REMOVED', 'Jake Hesketh' ],
  [ 'Southampton', 'REMOVED', 'Nathan Tella' ],
  [ 'Southampton', 'REMOVED', 'Alexandre Jankewitz' ],
  [ 'Southampton', 'REMOVED', 'Will Ferry' ],
  [ 'Southampton', 'REMOVED', 'Jacob Maddox' ],
  [ 'Tottenham Hotspur', 'ADDED', 'Joe Hart' ],
  [ 'Tottenham Hotspur', 'ADDED', 'Danny Rose' ],
  [ 'Tottenham Hotspur', 'ADDED', 'Cameron Carter-Vickers' ],
  [ 'Tottenham Hotspur', 'ADDED', 'Matt Doherty' ],
  [ 'Tottenham Hotspur', 'ADDED', 'Pierre-Emile Højbjerg' ],
  [ 'Tottenham Hotspur', 'ADDED', 'Jamie Bowden' ],
  [ 'Tottenham Hotspur', 'ADDED', 'Alfie Devine' ],
  [ 'Tottenham Hotspur', 'ADDED', 'Jack Clarke' ],
  [ 'Tottenham Hotspur', 'ADDED', 'Dane Scarlett' ],
  [ 'Tottenham Hotspur', 'REMOVED', 'Oliver Skipp' ],
  [ 'Tottenham Hotspur', 'REMOVED', 'Victor Wanyama' ],
  [ 'Tottenham Hotspur', 'REMOVED', 'Georges-Kévin Nkoudou' ],
  [ 'Tottenham Hotspur', 'REMOVED', 'Christian Eriksen' ],
  [ 'Tottenham Hotspur', 'REMOVED', 'Jan Vertonghen' ],
  [ 'Tottenham Hotspur', 'REMOVED', 'Alfie Whiteman' ],
  [ 'Tottenham Hotspur', 'REMOVED', 'Brandon Austin' ],
  [ 'Tottenham Hotspur', 'REMOVED', 'Troy Parrott' ],
  [ 'Tottenham Hotspur', 'REMOVED', 'Michel Vorm' ],
  [ 'West Bromwich Albion', 'ADDED', 'Sam Johnstone' ],
  [ 'West Bromwich Albion', 'ADDED', 'Darnell Furlong' ],
  [ 'West Bromwich Albion', 'ADDED', 'Kieran Gibbs' ],
  [ 'West Bromwich Albion', 'ADDED', 'Kyle Bartley' ],
  [ 'West Bromwich Albion', 'ADDED', 'Semi Ajayi' ],
  [ 'West Bromwich Albion', 'ADDED', 'Conor Townsend' ],
  [ 'West Bromwich Albion', 'ADDED', 'Ahmed Hegazi' ],
  [ 'West Bromwich Albion', 'ADDED', 'Dara Shea' ],
  [ 'West Bromwich Albion', 'ADDED', 'Jake Livermore' ],
  [ 'West Bromwich Albion', 'ADDED', 'Matt Phillips' ],
  [ 'West Bromwich Albion', 'ADDED', 'Kamil Grosicki' ],
  [ 'West Bromwich Albion', 'ADDED', 'Rekeem Harper' ],
  [ 'West Bromwich Albion', 'ADDED', 'Oliver Burke' ],
  [ 'West Bromwich Albion', 'ADDED', 'Romaine Sawyers' ],
  [ 'West Bromwich Albion', 'ADDED', 'Sam Field' ],
  [ 'West Bromwich Albion', 'ADDED', 'Hal Robson-Kanu' ],
  [ 'West Bromwich Albion', 'ADDED', 'Kenneth Zohore' ],
  [ 'West Bromwich Albion', 'ADDED', 'Matheus Pereira' ],
  [ 'West Bromwich Albion', 'ADDED', 'Charlie Austin' ],
  [ 'West Bromwich Albion', 'ADDED', 'Kyle Edwards' ],
  [ 'West Bromwich Albion', 'ADDED', 'Rayhaan Tulloch' ],
  [ 'West Ham United', 'ADDED', 'Grady Diangana' ],
  [ 'West Ham United', 'REMOVED', 'Roberto Jiménez' ],
  [ 'West Ham United', 'REMOVED', 'Albian Ajeti' ],
  [ 'West Ham United', 'REMOVED', 'Pablo Zabaleta' ],
  [ 'West Ham United', 'REMOVED', 'Carlos Sánchez' ],
  [ 'West Ham United', 'REMOVED', 'Chicharito' ],
  [ 'West Ham United', 'REMOVED', 'Xande Silva' ],
  [ 'West Ham United', 'REMOVED', 'Conor Coventry' ],
  [ 'West Ham United', 'REMOVED', 'Nathan Holland' ],
  [ 'West Ham United', 'REMOVED', 'Tomas Soucek' ],
  [ 'West Ham United', 'REMOVED', 'Joseph Anang' ],
  [ 'West Ham United', 'REMOVED', 'Jeremy Ngakia' ],
  [ 'West Ham United', 'REMOVED', 'Bernardo Rosa' ],
  [ 'West Ham United', 'REMOVED', 'Alfie Lewis' ],
  [ 'Wolverhampton Wanderers', 'ADDED', 'Matija Sarkic' ],
  [ 'Wolverhampton Wanderers', 'ADDED', 'Roderick Miranda' ],
  [ 'Wolverhampton Wanderers', 'ADDED', 'Ryan Bennett' ],
  [ 'Wolverhampton Wanderers', 'ADDED', 'Maximilian Kilman' ],
  [ 'Wolverhampton Wanderers', 'ADDED', 'Christian Marques' ],
  [ 'Wolverhampton Wanderers', 'ADDED', 'Lewis Richards' ],
  [ 'Wolverhampton Wanderers', 'ADDED', 'Leonardo Campana' ],
  [ 'Wolverhampton Wanderers', 'ADDED', 'Léo Bonatini' ],
  [ 'Wolverhampton Wanderers', 'REMOVED', 'Jesús Vallejo' ],
  [ 'Wolverhampton Wanderers', 'REMOVED', 'Taylor Perry' ],
  [ 'Wolverhampton Wanderers', 'REMOVED', 'Patrick Cutrone' ],
  [ 'Wolverhampton Wanderers', 'REMOVED', 'Max Kilman' ],
  [ 'Wolverhampton Wanderers', 'REMOVED', 'Morgan Gibbs-White' ],
  [ 'Wolverhampton Wanderers', 'REMOVED', 'Matt Doherty' ],
  [ 'Wolverhampton Wanderers', 'REMOVED', 'Benny Ashley-Seal' ],
  [ 'Wolverhampton Wanderers', 'REMOVED', 'Luke Cundle' ],
  [ 'Wolverhampton Wanderers', 'REMOVED', 'Owen Otasowie' ],
  [ 'Wolverhampton Wanderers', 'REMOVED', 'Ryan John Giles' ],
  [ 'Wolverhampton Wanderers', 'REMOVED', 'Leonardo Campana' ],
]

puts("Seeding team squad changes...")

players.each do |team_name, action, player_name|
  teams = Team.where("name like ?", "%#{team_name}%")
  players = Player.named(player_name)

  if teams.size == 1 && players.size == 1 then
    team = teams.first
    player = players.first

    player_season_info = PlayerSeasonInfo.current(player)
    if action == "ADDED" then
      player_season_info.team = teams.first
    elsif action == "REMOVED" then
      player_season_info.team_id = 1
    end
    player_season_info.save

    if !PlayerSeasonStat.where(player: player, season: Season.current).any? then
      puts player.name
      PlayerSeasonStat.create(player: player, season: Season.current)
    end
  end
end
